/*GESPA  Copyright (C) 2013  Jay Khurana
 * See GESPA License for additional information.
 */
package DNAFinderMain;

import java.awt.Color;
import javax.swing.text.*;
import java.util.regex.*;

/**
 *
 * @author Jay Khurana
 */
public class ReportTab extends javax.swing.JPanel {

    /**
     * Creates new form ReportTab
     */
    public ReportTab(String title, String report) {
        initComponents();
        jLabel1.setText(title);
        jTextArea1.setText(report);
    }
    
    public ReportTab(String title, String report, boolean aminoAcids){
        initComponents();
        StyledDocument colorDoc = new DefaultStyledDocument();
        jTextArea1.setDocument(colorDoc);        
        jTextArea1.setText(report);
        jLabel1.setText(title);
        SimpleAttributeSet[] amino = new SimpleAttributeSet[4];
        Pattern check = Pattern.compile(" [0-9]");
        Matcher m;
        for(int i=0; i<4; i++){
            amino[i]= new SimpleAttributeSet();
            if(i==0)
                StyleConstants.setForeground(amino[i], Color.ORANGE);
            else if(i==1)
                StyleConstants.setForeground(amino[i], Color.RED);
            else if(i==2)
                StyleConstants.setForeground(amino[i], Color.BLUE);
            else
                StyleConstants.setForeground(amino[i], Color.GREEN);
        }
        if(!aminoAcids){
            for(int i=0;i<colorDoc.getLength();i++){
                String c=report.substring(i,i+1);
                int limit=i+30;
                if(i+30>report.length()) 
                    limit=report.length();
                String colorAddCheck=report.substring(i,limit);
                m=check.matcher(colorAddCheck);
                if(!m.find()&&colorAddCheck.indexOf("   ")>-1)
                    continue;                
                switch(c){
                    case "A":
                        colorDoc.setCharacterAttributes(i, 1, amino[0], true);
                        break;                        
                    case "C":
                        colorDoc.setCharacterAttributes(i, 1, amino[1], true);
                        break;  
                    case "T":
                        colorDoc.setCharacterAttributes(i, 1, amino[2], true);
                        break;  
                    case "G":
                        colorDoc.setCharacterAttributes(i, 1, amino[3], true);
                        break;                          
                }
            }
            return;
        }
        
        for(int i=0; i<colorDoc.getLength();i++){
            String c=report.substring(i,i+1);
            int limit=i+30;
            if(i+30>report.length()) 
                limit=report.length();
            String colorAddCheck=report.substring(i,limit);
            m=check.matcher(colorAddCheck);
            if(!m.find()&&colorAddCheck.indexOf("   ")>-1)
                continue;
            name:
            switch (c) {
                case "A":
                case "V":
                case "F":
                case "P":
                case "M":
                case "I":
                case "L":
                case "W":                    
                    colorDoc.setCharacterAttributes(i, 1, amino[0], true);
                    break;
                case "D":
                case "E":
                    colorDoc.setCharacterAttributes(i, 1, amino[1], true);
                    break;
                case "R":
                case "K":
                    colorDoc.setCharacterAttributes(i, 1, amino[2], true);
                    break;
                case "S":
                case "T":
                case "Y":
                case "H":
                case "C":
                case "N":
                case "G":
                case "Q":                                       
                    colorDoc.setCharacterAttributes(i, 1, amino[3], true);
                    break;
            }
        }
        
    }
    public void changeReport(String s){
        jTextArea1.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1069, 499));

        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextArea1;
    // End of variables declaration//GEN-END:variables
}
